import OpenAI from "openai";
import { config } from "@config/index";
import { AIContext } from "@database/AIContext";
import { User } from "@database/User";
import { Guild } from "@database/Guild";
import { LogPriority, LogType } from "@database/Log";

export interface ChatMessage {
    role: "user" | "assistant" | "system";
    content: string;
}

export class AIService {
    private client: OpenAI;

    constructor() {
        if (!config.GROQ_API_KEY) {
            console.error("❌ CRITICAL: GROQ_API_KEY is missing from environment.");
        }
        this.client = new OpenAI({
            apiKey: config.GROQ_API_KEY,
            baseURL: "https://api.groq.com/openai/v1",
        });
    }

    private _getPersonalityPrompt(personality: string, nickname?: string): string {
        const base = `You are R3NDER, a smart Discord AI assistant. ${nickname ? `The user's nickname is "${nickname}".` : ""}`;
        
        switch (personality) {
            case "funny":
                return `${base} Your personality is witty, sarcastic, and hilarious. Use emojis and clever jokes.`;
            case "coder":
                return `${base} Your personality is a elite software engineer. You are technical, precise, and love talking about code and architecture.`;
            case "strict":
                return `${base} Your personality is a formal, strict, and highly professional administrative assistant. No jokes, just business.`;
            default:
                return `${base} Your tone is calm, professional yet slightly friendly (Siri-style). Keep responses concise.`;
        }
    }

    public async chat(userId: string, guildId: string, channelId: string, prompt: string, nickname?: string): Promise<string> {
        if (!prompt || prompt.trim().length === 0) {
            return "Please provide a valid prompt.";
        }

        try {
            // Fetch User and Guild data for Personality
            const userData = await User.findOne({ userId, guildId });
            const guildData = await Guild.findOne({ guildId });

            const tier = userData?.premiumTier || "free";
            const personality = guildData?.aiAutopilot?.personality || "normal";

            // Groq Free Model Assignment
            const model = "llama-3.1-8b-instant";
            let memoryLimit = 15;

            // Memory scaling (still using tiers for customization)
            if (tier === "pro") memoryLimit = 30;
            if (tier === "ultra") memoryLimit = 50;

            // Fetch chronological history
            const historyDocs = await AIContext.find({ userId, guildId })
                .sort({ createdAt: -1 })
                .limit(memoryLimit);
            
            const history: ChatMessage[] = historyDocs.map(doc => ({
                role: doc.role as any,
                content: doc.content
            })).reverse();

            const systemPrompt = this._getPersonalityPrompt(personality, nickname);

            const response = await this.client.chat.completions.create({
                model: model,
                messages: [
                    { role: "system", content: systemPrompt },
                    ...history,
                    { role: "user", content: prompt }
                ],
                temperature: 0.7,
                max_tokens: 1024,
            });

            let reply = response.choices[0].message?.content || "No response generated by AI.";

            // Personalized greeting (randomized)
            if (nickname && Math.random() < 0.2 && !reply.includes(nickname)) {
                reply = `${nickname}, ${reply}`;
            }

            // Persist for memory
            await AIContext.create([
                { userId, guildId, channelId, role: "user", content: prompt },
                { userId, guildId, channelId, role: "assistant", content: reply }
            ]);

            return reply;
        } catch (error: any) {
            console.error("AI ERROR:", error);
            const errorMsg = error.response?.data?.error?.message || error.message || "Unknown AI Provider Error";
            return `AI is temporarily unavailable. (${errorMsg})`;
        }
    }

    public async checkToxicity(content: string): Promise<boolean> {
        // Groq does not have a dedicated moderation endpoint in the OpenAI SDK wrapper.
        // Returning false for now as a bypass.
        return false;
    }

    public async isPrompt(content: string): Promise<boolean> {
        const questionKeywords = ["how", "what", "why", "where", "who", "when", "?", "help", "can you", "render", "ren"];
        return questionKeywords.some(key => content.toLowerCase().includes(key));
    }

    public async clearMemory(userId: string, guildId: string): Promise<void> {
        await AIContext.deleteMany({ userId, guildId });
    }
}
